### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ilyagr** [heywoodlh/nixos-configs#1]
I found a nice `teddit` config in this repo, but I'm not sure if I can use it. Could you add a license to the repo?

Thank you very much!

**Comment by heywoodlh** [comment]
This commit adds an MIT license: https://github.com/heywoodlh/nixos-configs/commit/4fcaef49f6fdbfc142d8894bfbb1c9dab5d02b03

Go crazy (and thanks for your efforts in being respectful of open source) :smile:
