### ISSUE TITLE
Anti-Patern Secret Use

### ISSUE THREAD

**Issue by Kreyren** [heywoodlh/nixos-configs#11]
Hey, https://github.com/heywoodlh/nixos-configs/blob/709550b39990c635e9c3c3ca2fac438337eb2718/nixos/roles/messaging/znc.nix#L4-L5 is an anti-patern as declaring that this way with readFile will make it readable by everyone who has access to your store (all users and if you deploy binary cache or do distributed builds then to the world)

Consider using ragenix with Post-Quantum plugin instead and refresh your secrets.

**Comment by heywoodlh** [comment]
Thanks for the tip! I wrote this a long while ago (when I was far less comfortable with Nix), and am no longer using ZNC, but will fix it ASAP.

**Comment by heywoodlh** [comment]
https://github.com/heywoodlh/nixos-configs/commit/a74eb67138c106d0a5308239dc61f41689738d0d
